### ISSUE TITLE
Some Suggested Improvements

### ISSUE THREAD

**Issue by BlakeTacklind** [HadaIonut/Foundry-Markdown-Importer#1]
Hey, cool repo.

This last weekend I was working on a project based on a some of yours and others work. I did figure out some extra things that would help this project out. Unfortunately I cant make them into a PR because I couldn't get the gulp to build. Something about gulp-concat missing arguments 😖 . But I could make some extra stuff work using the production code.

I have some suggestion:

## Proficiency

While the Proficiency calculation is cool and clever it is not quite right. There are some creatures that don't use their mod for attacks (example Lich). Fortunately there is a much simpler way to calculate proficiency. Use CR. Every creature in the SRD proficiency is based on the CR, I haven't found any exceptions. It is the same as character leveling.

```javascript
props['proficiency'] = Math.max(Math.floor((props?.data?.details?.challenge?.CR - 1) / 4) + 2, 2);
```
_Every 4 level increase by 1, minimum value is 2 at level 1_

_This might not apply to Tetra-Cube_

## Languages, Resistances, and Conditions

Languages, Resistances, and Conditions all have 2 parts to the object. `value` is a subset of some master list of string while `custom` is a string with `;` separated values. This produces correctly configured data.

For example
```
"languages": {
"value": [
  "goblin",
  "elvish",
  "common"
],
"custom": "Dog;Cat"
}
```

<details>
  <summary>Sets of strings</summary>

```javascript
default_languages = ['Aarokocra', 'Abyssal', 'Aquan', 'Auran', 'Celestial', 'Common', 'Deep speech', 'Draconic', 'Druidic', 'Dwarvish', 'Elvish', 'Giant', 'Gith', 'Gnoll', 'Gnomish', 'Goblin', 'Halfling', 'Ignan', 'Infernal', 'Orc', 'Primordial', 'Sylvan', 'Terran', 'Cant', 'Undercommon']
conditions_default = ['blinded', 'charmed', 'deafened', 'diseased', 'exhaustion', 'frightened', 'grappled', 'incapacitated', 'invisible', 'paralyzed', 'petrified', 'poisoned', 'prone', 'restrained', 'stunned', 'unconscious']
default_resistances = ['acid', 'bludgeoning', 'cold', 'fire', 'force', 'lightning', 'necrotic', 'piercing', 'poison', 'psychic', 'radiant', 'slashing', 'thunder']
```
_Thieves Cant is Cant_

<details>
  <summary>Approximate code I used</summary>

```javascript
var languages = [];
//Mostly is split with , but sometimes they have Common plus other languages
var custom_languages = propsTraits.languages.split(/(, | plus )/);
for (var i = custom_languages.length - 1; i >= 0; i--){
    //TODO why is the split parts being includes?
    if (custom_languages[i].match(/(, | plus )/)){
        custom_languages.splice(i, 1);
    }
    else if (default_languages.includes(custom_languages[i])){
        languages.push(custom_languages.splice(i, 1)[0].toLowerCase());
    }
}

//Empty value is just an empty string
if(languages.length == 0){
    languages = ""
}
//If only 1 element, just use a single string
else if (languages.length == 1){
    languages = languages[0]
}

//In structure:
languages: {
    value: languages,
    custom: custom_languages.join(";")
}
```

</details>
</details>

**Comment by HadaIonut** [comment]
Hi, thank you very much for the suggestions. 
I have never even realized that CR has the proficiency calculation built in, also the languages thing is smart, I pretty much gave up on making it work as indended by foundry.
I think it would be better if you would make a PR. Want me to help you with the gulp error? If you want and use Discord add me, I am assassinduke#0983

**Comment by BlakeTacklind** [comment]
I don't have time till this next weekend to work on this. But I will see what I can do.

**Comment by HadaIonut** [comment]
Hey, thx again for the suggestion, I managed to make time to implement your suggestions.
