### ISSUE TITLE
Custom damage resistance and immunities import incorrectly.

### ISSUE THREAD

**Issue by djohnsonnz** [HadaIonut/Foundry-Markdown-Importer#10]
Custom resistances/immunities break the preceding resistances/immunities and are imported as custom, due to the semicolon.

![image](https://user-images.githubusercontent.com/9582890/133914252-0743888a-444a-4585-86fd-677f822d0a6a.png)

![image](https://user-images.githubusercontent.com/9582890/133914258-12231417-93c8-45f5-8f50-837c4dbbde06.png)

As you're splitting resistances/immunities with ", " this also breaks the common custom resistance "; bludgeoning, piercing, and slashing from nonmagical weapons" 

![image](https://user-images.githubusercontent.com/9582890/133914333-40172782-c9d0-4ca2-bd63-0bf35c71a76e.png)

**Comment by HadaIonut** [comment]
Fixed in newest update
