### ISSUE TITLE
Can only import creatures with Innate Spells

### ISSUE THREAD

**Issue by djohnsonnz** [HadaIonut/Foundry-Markdown-Importer#11]
As a side effect of adding support for Innate spells it seems now any creature that does not have them cannot be imported.

![image](https://user-images.githubusercontent.com/9582890/133927535-54df64e7-f075-489c-b565-18cff60c7de0.png)

![image](https://user-images.githubusercontent.com/9582890/133927552-bb69c2de-0385-4ca8-ae15-e5bb460e8e1a.png)

**Comment by HadaIonut** [comment]
Yeah, I found that, it's fixed now
