### ISSUE TITLE
"Import" button doesn't open importer

### ISSUE THREAD

**Issue by PlutoHimself** [HadaIonut/Foundry-Markdown-Importer#2]
When I click the button in the actors panel, the following message is printed to the console:

Error: An error occurred while rendering ImportWindow 59: No data was returned from template modules\Tetra-Cube-Importer\templates\importer.html

**Comment by HadaIonut** [comment]
Hi, for some reason I cannot reproduce that error. Can you please tell me if the file from `modules\Tetra-Cube-Importer\templates\importer.html` exists? Or if this path is wrong for some reason.

**Comment by PlutoHimself** [comment]
The file exists at that location and only contains the following lines: 

`<div>`
`  <div class="import-options">Markdown Text</div>`
`  <textarea class="text-input" name="text" style="white-space: pre-wrap"></textarea>`
`</div>`

**Comment by HadaIonut** [comment]
The content is correct, and if the file path exists then i really have no ideea what is causing this error. I will try to make a few changes and send you a test build since i cannot replicate this. Add me on discord: assassinduke#0983

**Comment by Miennai** [comment]
I have the same problem. The module works on my desktop app, but not on the game I run through https://forge-vtt.com. I can't speak for any other hosting service or other methods.

**Comment by HadaIonut** [comment]
Okey, then I know I should bother Kakaroto. I am guessing its a permission problem but I am not sure what I should do to fix it. Hope I will come back with a fix ASAP.
