### ISSUE TITLE
Skills with spaces in the name cause an error

### ISSUE THREAD

**Issue by tigator** [HadaIonut/Foundry-Markdown-Importer#5]
First off, THANK YOU for this module, it's had a very high success rate and saved me a lot of time as a DM.

**Versions:** Foundry 0.7.9, dnd5e 1.2.4

**Issue description:** If markdown I'm attempting to import includes the Animal Handling and/or Sleight of Hand skills, that skill comes in blank with a NaN modifier, and the Initiative modifier will also show NaN.  Errors will be thrown mentioning all of the abilities/actions on the sheet, however upon closing and reopening the Actor in Foundry, those items usually will have been created correctly.

**Workaround:** Delete the offending skill from the markdown you are trying to import, and add the skill manually after import.

**To reproduce:** Try importing the following markdown, and you will receive errors for all of the abilities on the sheet.  Then remove the text "Animal Handling +4, " and retry the import, and it will work without issue.
```
___
> ## Test Creature
>*Medium humanoid, chaotic good*
>___
>- **Armor Class** 13
>- **Hit Points** 37 (6d8 + 10)
>- **Speed** 30 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|13 (+1)|12 (+1)|14 (+2)|10 (+0)|14 (+2)|13 (+1)|
>___
>- **Skills** Animal Handling +4, Nature +2, Perception +4
>- **Senses** passive Perception 14
>- **Languages** Common plus any one language
>- **Challenge** 1 (200 XP)
>___
>***Innate Spellcasting.*** The creatures's innate spellcasting ability is Wisdom (spell save DC 14). The creature can innately cast the following spells, requiring no material components: 1/day each: *bane*, *false life*  
>
>
>***Speak with Plants.*** The creature can communicate with plants as if they shared a language.  
>
>### Actions
>***Multiattack.*** The creature makes two melee attacks with its stick and uses Test Ability.
>
>***Stick.*** *Melee Weapon Attack:* +3 to hit, reach 5 ft., one target. *Hit:* 4 (1d6 + 1) piercing damage.  
>
>***Test Ability.*** The creature chooses one plant it can see within 30 feet of it. If the plant can hear the creature, the plant uses its reaction to make one melee attack against a target that the creature can see.
```

**Comment by HadaIonut** [comment]
Hi, managed to reproduce the problem and I am working on a fix.

I will close this issue when the patch is live
