### ISSUE TITLE
Doesnt import certain Statblocks

### ISSUE THREAD

**Issue by RandomLegend** [HadaIonut/Foundry-Markdown-Importer#6]
Hello,

i just updated to 0.8.7 and updated all my modules.
I now wanted to import some custom statblocks and nothing happened.

I then used some preset statblocks on the site to check if i made some mistake in my block that couldnt be imported. Ancient Black Dragon for example works perfectly fine. I then tried some other MM presets like Mastiff and Ogre and those both didnt work either.

Thats the issue i get for example when i try to import the mastiff.
![grafik](https://user-images.githubusercontent.com/38812603/122428098-eb4f9180-cf91-11eb-86f1-ef80a6f9e25e.png)

Can you help me out here?

**Comment by RandomLegend** [comment]
i just installed the 1.1.2 Version of your module manually and it now "imports" the statblock, but throws out a whole bunch of errors and the statblock is missing nearly everything as you can see here: 
![grafik](https://user-images.githubusercontent.com/38812603/122428958-ac6e0b80-cf92-11eb-8e60-7ae960366bcd.png)

**Comment by HadaIonut** [comment]
Hi, I think you may be using an older version of the module, the current module version is 1.2.2. 

But if that was a typo please go to https://pastebin.com/ and paste the markdown you are using and give me the link to the paste.

**Comment by RandomLegend** [comment]
Hey, thanks for the reply. I used both the newest version (thats the 1st. image where i dont get any import, but that small error in the console) and the previous version (2nd image with many errors and a faulty import)

You can grab the markdown i used when you try to import the ogre preset from tetra-cube or the mastiff for example. The ancient black dragon worked interestingly.
So i get very mixed results but the very most stats dont import and only the ancient dragon i tried worked.

**Comment by HadaIonut** [comment]
I have fixed the error, the update is going live soon

**Comment by RandomLegend** [comment]
Nice, thank you!
