### ISSUE TITLE
Import failure, overcome by adding one sense before passive perception

### ISSUE THREAD

**Issue by Jussisa-Tot** [HadaIonut/Foundry-Markdown-Importer#7]
Hi there,

First time reporting issues on Github at all so apologies if this has been covered already.

Foundry version 0.8.6
DnD 5th Edition 1.3.5
Tetra-Cube Importer 1.2.3

I tried importing some custom creatures from the Tetra Cube and noticed some of them were failing. After comparing a few of the imports, I noticed that one difference was the senses. It would appear that adding a random sense with a value before the passive perception allows the import to complete - not sure if that is helpful or not.

![image](https://user-images.githubusercontent.com/86168101/122653687-2f7f9500-d13e-11eb-8fb7-729e9b9c3338.png)

Thanks for your hard work!

**Edit**

I have found an instance whereby my above fudge doesn't work.

![image](https://user-images.githubusercontent.com/86168101/122655227-cd785d00-d148-11eb-8b8d-e569643add54.png)

**Comment by HadaIonut** [comment]
It would be useful if you could make me a paste bin of the creatures that fail to import. Paste here the markdown for the creatures that cause errors https://pastebin.com/

**Comment by Jussisa-Tot** [comment]
See below. shall I add a new comment per creature, as and when I find them?
https://pastebin.com/eWBws24y

**Comment by HadaIonut** [comment]
No, i think it's fine for now, those errors should be fixed by the update that is going live in a bit. If you find any more problems open another issue
