### ISSUE TITLE
Importing Innate Spellcasting spells

### ISSUE THREAD

**Issue by djohnsonnz** [HadaIonut/Foundry-Markdown-Importer#8]
When importing a creature Innate Spellcasting spells are not imported to the spelllbook.

**Comment by HadaIonut** [comment]
it's somewhat fixed in the next update, I am not sure how you make spells be at will or castable once a day, but the list gets populated at least

**Comment by djohnsonnz** [comment]
There is a field "Spell Preparation Mode" on a spell which you can set to "Innate Spellcasting". There's also a "Limited Uses" option under Spellcasting which you can set number of uses per day, short rest, etc.

![image](https://user-images.githubusercontent.com/9582890/133926186-f9f7ffdf-5396-4bd3-9699-7bd009235d33.png)

![image](https://user-images.githubusercontent.com/9582890/133926326-5200e7e3-e369-4cee-93dd-adf1f2c6a031.png)

**Comment by HadaIonut** [comment]
Interesting, now I just have to see how I configure that from code

**Comment by djohnsonnz** [comment]
I exported the JSON from a spell after setting it to Innate, I believe this is what you are looking for.

![image](https://user-images.githubusercontent.com/9582890/133926706-3ef87638-95ac-4abd-895b-22c922d02f17.png)

**Comment by HadaIonut** [comment]
yup, looks like what I would imagine, I'll implement that later and notify this thread when I am done

**Comment by HadaIonut** [comment]
It should be working now
