### ISSUE TITLE
Skill proficiencies importing with expertise

### ISSUE THREAD

**Issue by djohnsonnz** [HadaIonut/Foundry-Markdown-Importer#9]
When importing skills the proficiency bonus is not taken in to account, therefore skills are imported as having expertise when they don't.

Example below.

![image](https://user-images.githubusercontent.com/9582890/133911312-5488c4ac-c933-4928-b69f-58490f3c9139.png)

![image](https://user-images.githubusercontent.com/9582890/133911317-bb05a28e-b895-4b7d-b04e-adbba584cf6b.png)

If I subtract the proficiency bonus from the skill (in this case 2) this imports correctly.

![image](https://user-images.githubusercontent.com/9582890/133911334-303211b7-f1db-42aa-a748-5b9d274e5377.png)

![image](https://user-images.githubusercontent.com/9582890/133911346-ae5fcd4f-d66c-4b13-a1cc-2de92626bdcd.png)

**Comment by HadaIonut** [comment]
Fixed in newest update
